### ISSUE TITLE
Web-based frontend not loading

### ISSUE THREAD

**Issue by FumbleNL** [cloudradar-monitoring/rport#203]
Hi, I followed all steps in the manual and added the web front-end files. However, when accessing the web frontend (port 3000) I only see a loading circle animation. I verified the network tab in Chrome, however, there are no errors.  Also, the rport.log does not contain any errors. I am using chrome 89.

**Comment by m-terel** [comment]
Hi, @FumbleNL. I'm sorry that you are having issues. I would be happy to help you.

Sorry, did you mean `rportd.log`? Can you please provide some screenshots? Because I couldn't reproduce it.

**Comment by FumbleNL** [comment]
Hi, @m-terel I did some more testing and I found out that it is a browser issue. It works in Firefox, however not in Google Chrome. See attached screenshot. Let me know if you need more information.

![Screenshot 2021-05-01 09 23 39](https://user-images.githubusercontent.com/83034560/116774765-12dcb000-aa5f-11eb-9bf6-ffe2723674b8.png)

**Comment by kevineichhorn** [comment]
@FumbleNL it seems like instead of the JS build some kind of HTML is loaded instead (indicated by the uncaught syntax error '<' in your console). 

So one possiblity why that is, is that it loads the 404 page instead, since the requested build files are seemingly missing.

But since the UI is working for you in Firefox, I suspect that the reference the .js files was just wrongly cached by Chrome. It's a shoot in the dark but can you try to hard reload the page/clear your browser cache?

If that doesn't help, can you do the same in Firefox. Because this is most likely not a browser issue and to solve this we kinda need to get a consistent result between both browsers.
