### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by cmprmsd** [cloudradar-monitoring/rport#441]
Hey! 

Is UDP support planned and on your roadmap? 
Just opening this issue to keep track of the feature status. :)

That's something that would not work through the SSH libraries as the protocol does not support it.

**Comment by thorstenkramm** [comment]
@cmprmsd UDP is fully supported since [0.5.8](https://github.com/cloudradar-monitoring/rport/releases/tag/0.5.8). You can test with the latest pre-release. SSH is just a "base skeleton". We do a lot more than plain SSH tunnels. 
We are planning to release the next [stable version 0.6.0](https://blog.rport.io/2022/02/rport-060-announced.html) in February 2022. 

Just for curiosity and maybe for extending our automated tests. What udp-based application or protocol to you want to reach through the UDP tunnel?

**Comment by cmprmsd** [comment]
Cool! 

QUIC and WireGuard e.g. :)
Some people also rely on 161-snmp
