### ISSUE TITLE
Client install argument creates start script that runs as root

### ISSUE THREAD

**Issue by Flachdachs** [cloudradar-monitoring/rport#466]
I know that Debian 7.1 is not a supported system. However, I was able to compile an ARM binary that runs fine when starting manually on that old machine.

The client has a `--service install` option that creates a start script for the old `/etc/init.d` system. There is also an option for `--service-user` with a default value. But whether or not you use this option there isn't a command that changes the user in the created start script. So when you use this script to start the rport client is stops with "By default running as root is not allowed." as message in the error log.

Is this an issue that happens also in supported versions or can it be fixed easily regardless the unsupported version?

**Comment by thorstenkramm** [comment]
@Flachdachs 
Thank you for bringing this issue to our attention.
We are using a [third-party library to create autostart scripts](https://github.com/kardianos/service) for all operating systems. This library is not reliable on Linux without Systemd. It also creates faulty rc-scripts on Alpine. 
We will not attempt to fix it either on our code base nor on the upstream project because Linux without Systemd is pretty outdated and fixing it manually is trivial. Just open the init-script with an editor and enter the correct username.

**Comment by Flachdachs** [comment]
For the protocol: One fix is to prefix the command that is started in the `start)` section with `sudo -u rport` or whatever user it should be. The script is written without a variable or anything else that contains the username. So you have to write it literally or crate a variable yourself.
