### ISSUE TITLE
Feature : new config entry to define the ip/domain where the tunnel is located

### ISSUE THREAD

**Issue by AC-WhiteGlint** [cloudradar-monitoring/rport#469]
Hi,

I came accross an issue when using rport api behin a https reverse proxy who is also behind cloudflare which I am using to protect all my app.
When connecting to the web console and creating a tunnel it used the FQDN, the problem is that the api is behing cloudflare services, which then resolve to cldouflare ips.
It could be greate to have anohter entry in the config to specific the ip/fqdn where the tunnel is so that we can connect to the servers/computer even when using service like cloudflare to protect the api.

**Comment by thorstenkramm** [comment]
@AC-WhiteGlint I get your point.
We have http(s) tunnels where RPort itself acts as a reverse proxy to always inject proper certificates. With the upcoming version 0.6.0 we introduce VNC and RDP over web, which also requires valid certificates.  
If you want to access the end of a tunnel on a different hostname other than the API, you must maintain two certificates. 

Your request is using absolute URLs instead of relative URLs for opening the tunnels, with the option to set a custom FQDN just for the tunnel links.

BTW: You can protect your API with fail2ban. https://oss.rport.io/docs/no10-securing-the-server.html

**Comment by AC-WhiteGlint** [comment]
> Your request is using absolute URLs instead of relative URLs for opening the tunnels, with the option to set a custom FQDN just for the tunnel links.

Yes exactly, this would be great, do you think this is something you could add?

**Comment by AC-WhiteGlint** [comment]
Thank you for this.

However when I enabled the option, the link for the RDP connection are not being updated and they are still point towards the FQDN of the API which is behind cloudflare.

I am doing somehting wrong there.

I double check and the container is using the latest version of rportd

**Comment by thorstenkramm** [comment]
This feature has not been release yet. The backend of the preview-release can handle the new setting. But the frontend is not using it yet. You must wait for the next release of the frontend. We are working hard on it.
