### ISSUE TITLE
Question about pairing.rport.io & Feature Request: show current "Logged on user"

### ISSUE THREAD

**Issue by reeyon** [cloudradar-monitoring/rport#474]
Hi,

Why is generating an installer script is going thru a centralized platform (https://kb.rport.io/connecting-clients#how-is-the-pairing-working)? Do you have all of our information each time user is generating the installer scripts?
Since we have ```client id``` , ```password```, ```server``` information, can we generate the installer script locally on the server?

Feature request: add ``Current Logged on User" in the client detail.

**Comment by thorstenkramm** [comment]
@reeyon 
Using the central pairing service optional. You can attach clients to your server by downloading the client and creating the config file manually.
The central pairing service is for your convenience. It does not store the data. You deposit some values, which are held in memory and deleted after five minutes.
We are working on publishing the [pairing service as an open-source package](https://github.com/cloudradar-monitoring/rport-pairing) too, so shortly you will be able to self-host the pairing service on your rport server. 

Your feature request is stored.

👉 **Next time, make sure**:
1. Do not put two topics into a single issue, thread or message. Create individual issues for each. Otherwise, not possible to follow up. 
2. Do not create an issue for question. Use the [Discussions](https://github.com/cloudradar-monitoring/rport/discussions) for that.
