### ISSUE TITLE
Feature Request: RDP autoscale, Scheduler, IPV6

### ISSUE THREAD

**Issue by wKollendorf** [cloudradar-monitoring/rport#512]
Hello,

thanks for the great project! I know the scheduler is being worked on right now. Are there any plans for ipv6 and RDP autoscale? That were two things I was missing while playing with rport. IPv6 is mostly enabled on the machines I am using for remote connection to the clients, so the tunnels have to be unrestricted right now. The autoscale ability would be great, maybe it is also possible to integrate the "RDP via browser" into the web UI as an alternative to the separate window? And what about a more granular user management for restricting specific user to limited actions? Also it would be great to be able to edit existing tunnels.

**Comment by thorstenkramm** [comment]
@wKollendorf All these ideas are understandable and worth discussing. 
Please create separated posts for each idea on the [discussion forum](https://github.com/cloudradar-monitoring/rport/discussions/categories/roadmap-feature-wishes-ideas). 
Mixing two or more ideas in one thread makes answering, up voting and following up really hard.
I'll close this because it's not an issue. Let's move it to a discussion.
