### ISSUE TITLE
Move the rport server to a different machine

### ISSUE THREAD

**Issue by vagner-dias** [cloudradar-monitoring/rport#528]
Hi!

I am using rport for some months and the product is really awsome. Everything works smoothly.

I will keep the URL on the new location (just repoint the DNS to the new IP) but my question is: Will the new clients connect to the new server (since they are connecting to the DNS name) or do I have to execute some procedure to move everything to this new server ?

**Comment by thorstenkramm** [comment]
@vagner-dias If the clients connect to a DNS with a hostname like `*.users.rport.io` you must change it in the rport.conf on each client. As soon as the DNS record is deleted, your clients would disconnect otherwise. 
You can change the server address of a client from the rport dashboard with a script that changes the string in the file using `sed` for example. 
**Do not restart the client over the rport connection.** That would kill the client immediately and the script will not finish. 
You must restart the client after the script has finished. For example:
```
echo "systemctl restart rport"|at now +1minute`
```

**Comment by vagner-dias** [comment]
Great, thanks!

**Comment by geoynomous** [comment]
I could not find documentation how to actually move the rport server to a different machine?
