### ISSUE TITLE
launch tunnel with null as servername

### ISSUE THREAD

**Issue by tscheiber5** [cloudradar-monitoring/rport#544]
Hello,

First of all I have to say that I like RPort very much and would recommend it to all MSPs.

After updating the server to 0.7.0 I experience the following issue.
when creating a tunnel (to any port) and then trying to launch the tunnel with the >_ sign the link looks like https://null:23456
The tunnel is working fine when you replace the "null" with the correct rport-server name.

Thanks and keep up the good work!
Thomas

**Comment by tscheiber5** [comment]
Oh, I forgot to mention that new installations on Windows clients are unsuccessful.

_Start-Service : Service 'Rport Client (rport)' cannot be started due to the following error: Cannot start service
rport on computer '.'._

**Comment by thorstenkramm** [comment]
@tscheiber5 Thank you for bringing this issue to our attention. Others have reported that, too.
🚒 We are working on a hotfix. **The fix is expected for today 2022-05-23.**

Check this page https://download.rport.io/frontend/stable/
We will create a new 0.7.0 release with a build number greater than 1022. 
Just download and unpack to `/var/lib/rport/docroot/`. The issue is related to the JS files only. The server binary does not need any update.

**Comment by thorstenkramm** [comment]
@tscheiber5 Next time, please do not report two issues in a single threat. That makes following up hard.

**Comment by tscheiber5** [comment]
@thorstenkramm Danke fuer die prompte Antwort.

**Comment by thorstenkramm** [comment]
This has been fixed. The bad windows binary has been replaced.

**Comment by thorstenkramm** [comment]
@dimitribellini 
No. The ZIP file is, in fact, broken. The frontend code is built on Bitbucket. Their CDN has some issues currently. Hopefully the download is fixed in a couple of hours.

**Comment by dimitribellini** [comment]
@thorstenkramm thanks so much!

**Comment by dimitribellini** [comment]
@thorstenkramm the latest version of the ZIP is now working! Thanks so much for the quick fix

**Comment by tscheiber5** [comment]
@thorstenkramm thanks for the quick fix, the tunnels are launching properly again.
