### ISSUE TITLE
Getting a weird issue with the config file.

### ISSUE THREAD

**Issue by samjaninf** [cloudradar-monitoring/rport#618]
Hey,
I am trying to use rport in a docker container but I keep getting a mssage like:
`2022/07/06 20:10:18 Invalid config: error reading config file: While parsing config: (18, 23): no value can start with $. See --help`

I was wondering if I could get some information on where to look. Is the 18, 23 the lines in the file? There is no $ in the config file so I'm not quite sure what it's asking for. I've tested it by running: `./rportd -c rport-conf.conf` which doesn't run becaues of user issues, but it does not report any errors.

version: rportd_0.8.0_Linux_x86_64.tar.gz

**Comment by thorstenkramm** [comment]
Yes. It means error on line 18 position/character 23. 
If you want to run rport in the foreground try
`su - rport -s /bin/sh -c "rportd -c rport-conf.conf"`

I'll close this issue because there is no issue with rport. 
Next time, please use the [discussions](https://github.com/cloudradar-monitoring/rport/discussions) to ask for help.
