### ISSUE TITLE
Feature Request: Session Recording and Workflow Authorization

### ISSUE THREAD

**Issue by blitz9826** [cloudradar-monitoring/rport#653]
Rport is a phenomenal project and has the potential to become a great PAM solution (basically credential vault + proxied connections to servers/services, often with session recording, MFA, and workflow authorization). JumpServer is another open source solution which does this but the overlap between these two projects is significant enough that if Rport offered these two features, JumpServer would become redundant (well that with the fact there's a huge language barrier makes Rport that much more worthwhile).

**Comment by thorstenkramm** [comment]
@blitz9826 I assume to refer to SSH. Right?
Session recording on SSH is anything but trivial. It could be considered as a security breach by design. 
Implementing session recording on the client and not as a man in the middle would be a secure solution.
Do you know how [Jumpserver](https://www.jumpserver.org/index-en.html) implements session auditing? Does it work with any SSH client?
