### ISSUE TITLE
Installer Compatibility with PS 2.0

### ISSUE THREAD

**Issue by adriangalbincea** [cloudradar-monitoring/rport#775]
We still have Windows 7 machines or Server 2008/R2/SBS2011 that must stay on PS 2.0. Please adjust the script for more compatibility.
**Invoke-WebRequest** command does not exist in PS 2.0
**[parameter(Mandatory)]** must have a value. E.g. **[parameter(Mandatory = $false)]**

**Comment by thorstenkramm** [comment]
@adriangalbincea I understand your request. But PS 2 is really damn old. 
Implementing PS2 compatibility on the open-source version will distract our team from developing features for the broad user base. 
But we can implement it for you if you sign up for a support contract. 
Sorry everybody. We avoid using GitHub for sales. I just want to offer help and the project needs funding. Please [ping me personally](https://de.linkedin.com/in/thorsten-kramm-92306b128).

**Comment by adriangalbincea** [comment]
It is damn old but you have to adapt to the real market and not the one you might dream of. I am not confortable either to keep this shitty servers but I have to. I was thinking to migrate from splashtop 2000 machines but I will think again if I really want to after seeing your reply.
Thanks!

**Comment by thorstenkramm** [comment]
What's wrong with my reply? I'm offering help. 
We are not volunteers sponsored by donations. I know that old systems must be supported. But we have a long list with feature requests. Why do you think you shut be treated with priority?
Our support contract costs you a fraction of splashtop, and we don't put limits on users or devices. 
You are welcome to adapt the script to PS2. It's open source. I'm happy to integrate it into the public pairing service.

**Comment by herzkerl** [comment]
In case you didn’t know (I didn’t since a few minutes ago, searching for a way to install RPort on 2008 R2), there’s an official download for ‚Windows Management Framework 5.1‘ (which contains PowerShell 5.1) available for Windows Server 2008 R2 and Windows 7.

After installing KB3191566 and restarting the server, installing RPort worked—without any warnings or errors. 

Link: https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/setup/install-configure?source=recommendations&view=powershell-7.3

**Comment by adriangalbincea** [comment]
@herzkerl is case you did not know, SBS servers or some old servers can't even get PS 3.0 because will break some functionalities.
